site_name: concave_hull
site_url: https://concave_hull.readthedocs.io
site_description: A very fast 2D concave hull algorithm, for python.
site_author: district10

repo_url: https://github.com/cubao/concave_hull
edit_uri: blob/master/docs/

theme: readthedocs
nav:
  - Home: index.md
  - Usage: usage.md
  - WGS84: wgs84.md
  - About:
      - Release Notes: about/release-notes.md
      - License: about/license.md
plugins:
  - include-markdown
copyright: Copyright &copy; 2023 <a href="https://cubao.readthedocs.io/">cubao team</a>.
